name: Manual Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (optional - uses current package.json version if not specified)'
        required: false
        type: string

env:
  NODE_VERSION: '22'

jobs:
  publish:
    name: Manual Publish to npm
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # for npm provenance
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: |
          pnpm typecheck
          pnpm lint
          pnpm test:run
          pnpm build

      - name: Update version (if specified)
        if: github.event.inputs.version != ''
        run: |
          pnpm version ${{ github.event.inputs.version }} --no-git-tag-version
          echo "Updated package.json to version ${{ github.event.inputs.version }}"

      - name: Publish to npm
        run: pnpm publish --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}